name: CI

on: 
  pull_request:
    branches: 
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies 
      run: |
        echo Create Virtual Environment
        python3 -m pip install --user --upgrade pip
        python3 -m venv env 
        echo Activate Environment
        source env/bin/activate
        echo Install Dependencies (requirements.txt)
        pip3 install -r requirements.txt
    - name: Run Python Tests
      run: |
        pytest
        echo Deactivate Environment
        deactivate
    - name: Other
      run: | 
        echo Lint scan 
        echo Add www-data to group for files 
        echo Set permissions for files 
        echo Start service (gunicorn)
        echo Enable service 
        echo Restart Nginx

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
