name: CI

on: 
  pull_request:
    branches: 
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Starting Build
      run: echo Starting Build
    - name: Build Commands
      run: |
        echo Create Virtual Environment
        python3 -m pip install --user --upgrade pip
        python3 -m venv env 
        echo Activate Environment
        source env/bin/activate
        echo Install Dependencies (requirements.txt)
        pip3 install -r requirements.txt
        echo Run Tests
        echo Deactivate Environment
        deactivate
        echo Add www-data to group for files 
        echo Set permissions for files 
        echo Start service (gunicorn)
        echo Enable service 
        echo Restart Nginx
